### ISSUE TITLE
[Feature]: Env variable capture for dstack.yml files

### ISSUE THREAD

**Issue by spott** [dstackai/dstack#1000]
### Problem

When I want to add an environment variable to my dstack run, I need to either add it using the command line, or hardcode it into the .dstack.yml file.

This poses a problem for secrets, as well as just being annoying to deal with.

### Solution

When writing a .dstack.yml file, any env variable that is passed without a value in the `env` block is inherited from the environment.

So:
```yml
type: task

python: "3.11"
env:
  - HF_HUB_ENABLE_HF_TRANSFER=1
  - WANDB_API_KEY
commands:
  - pip install -r fine-tuning/qlora/requirements.txt
  - python fine-tuning/qlora/train.py

# (Optional) Configure `gpu`, `memory`, `disk`, etc
resources:
  gpu: 80GB
```
takes the current value of `WANDB_API_KEY` from the users environment, while `HF_HUB_ENABLE_HF_TRANSFER` is set to `1`, even if it is in the users environment.

### Benefit

Better secret management, easier env management.

### Alternatives

passing in arguments, leaving .dstack.yml out of git.

### Would you like to help contributing this feature?

Yes

**Comment by r4victor** [comment]
@spott, thanks for the issue! There is certainly a need to conveniently pass sensitive data to runs. I like the approach you're suggesting with omitting the env value. However with the straightforward implementation that involves including omitted values into `env`, there is still a problem with sensitive data being included in run spec – stored and passed as plaintext.

dstack used to have secrets feature that should address you problem. The idea is to have a CLI command that allows users to add secrets to repo like this:

```
dstack secrets add [-y] NAME [VALUE]
```

Then all runs in the repo will get their environment populated with the configured secrets automatically.

@spott, will this approach work for you? I saw you're working on the PR. If we go the secrets route, our core team can take this issue since it may involve a bit more work.

**Comment by spott** [comment]
I think the "fill in the env" part that I added here: (https://github.com/dstackai/dstack/pull/1003) is still useful, even if it isn't useful for high-sensitivity secrets.

I would probably use something like `dstack secrets add`, though I'm not super happy about having yet another secrets manager to manage... I currently use 1password, which puts secrets into my environment for a specific project.

I think rather than creating your own separate discrete secrets manager, something that is closer to using a `.env` file or just using the environment and denoting secrets separately makes more sense.

Something like (this is very rough):

```
type: task

python: "3.10"

env:
  - NOT_A_SECRET="yes"
  - ANOTHER_NOT_SECRET_FROM_USERS_ENV
secrets:
  - DEFAULT_TO_ENV_VARIABLE="yes, you can write them in .dstack, but probably shouldn't"
  - SECRET_ENV_TAKEN_FROM_USERS_ENV_OR_DOTENV
  - type: file
      path: my_secret_file.json
  - type: env  #maybe something like this to be more explicit? not sure if necessary
      name: ENV_VARIABLE
      source: .env
  - type: aws_secret # to use an integration?
      name: my_aws_secret
      target: <some spec that tells where to drop the secret>

commands:
  - do_stuff_with_secrets.sh
```

In this case, "secrets" are defined in the .dstack.yml file and either defined there (for those who like to live dangerously, or aren't checking in their .dstack.yml files), or defined in the local environment, or defined in a `.env` file for the project, or you can add integrations with other secret managers.

This way I don't have to "register" secrets with your specific tool, I can just use the tools that I typically use and things "just work".
