### ISSUE TITLE
[Bug] The `shm_size` property in `resources` doesn't take effect

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1006]
Steps to reproduce:

1. Define `.dstack.yml`

```yaml
type: dev-environment

python: 3.11

ide: vscode

resources:
  shm_size: 4GB
```

2. `dstack run . -b aws`

3. Inside the dev environment, run `df -h /dev/shm`

It prints:

```
Filesystem      Size  Used Avail Use% Mounted on
shm              64M     0   64M   0% /dev/shm
```

> [!NOTE]
> If I `ssh <run name>host`, and run `docker inspect <container id> | grep -i shm`, it prints:
> ```
> "ShmSize": 67108864,
> ```
