### ISSUE TITLE
[Bug]: Suspiciously low price for `A100:8:80GB` on `azure`

### ISSUE THREAD

**Issue by alvarobartt** [dstackai/dstack#1044]
### dstack version

0.16.5

### Python version

3.11

### Host OS

macOS

### Host Arch

arm64

### What happened?

When running `dstack run` on a file with the content below, the price parsing seems to fail for Azure and it displays a wrong price e.g. ~ 4 USD while real applied price is ~ 14 USD (see screenshot below)

```yaml
...
resources:
  gpu:
    name: A100
    memory: 80GB
    count: 8
```

<img width="1512" alt="image" src="https://github.com/dstackai/dstack/assets/36760800/5e9b0a4f-7bfc-4c40-b265-01ab85946a78">
