### ISSUE TITLE
[Bug]: Services with OpenAI mapping fail if chat_template or eos_token are not specified

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#1110]
### Steps to reproduce

Run a service with openai mapping:

```
type: service

image: ghcr.io/huggingface/text-generation-inference:latest
env:
  - MODEL_ID=mistralai/Mistral-7B-Instruct-v0.1
port: 80
commands:
  - text-generation-launcher --port 80 --trust-remote-code

resources:
  gpu: 24GB

# (Optional) Enable the OpenAI-compatible endpoint
model:
  format: tgi
  type: chat
  name: mistralai/Mistral-7B-Instruct-v0.1
```

The CLI emits an error when submitting a run. The bug introduced in https://github.com/dstackai/dstack/pull/944.

### Actual behaviour

```
✗ dstack run . -f .dstack/confs/openai.yaml
 Configuration          .dstack/confs/openai.yaml    
 Project                main                         
 User                   admin                        
 Pool name              default-pool                 
 Min resources          2..xCPU, 8GB.., 1xGPU (24GB) 
 Max price              -                            
 Max duration           -                            
 Spot policy            auto                         
 Retry policy           yes                          
 Creation policy        reuse-or-create              
 Termination policy     destroy-after-idle           
 Termination idle time  600s                         

 #  BACKEND  REGION        INSTANCE       RESOURCES             SPOT  PRICE       
 1  gcp      us-central1   g2-standard-4  4xCPU, 16GB, 1xL4     yes   $0.223804   
                                          (24GB), 100GB (disk)                    
 2  gcp      europe-west4  g2-standard-4  4xCPU, 16GB, 1xL4     yes   $0.246734   
                                          (24GB), 100GB (disk)                    
 3  gcp      europe-west1  g2-standard-4  4xCPU, 16GB, 1xL4     yes   $0.25199    
                                          (24GB), 100GB (disk)                    
    ...                                                                           
 Shown 3 of 142 offers, $5.876 max

Continue? [y/n]: y
GatewayError: 2 validation errors for OpenAIOptions
model.tgi.chat_template
  Input should be a valid string [type=string_type, input_value=None, 
input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
model.tgi.eos_token
  Input should be a valid string [type=string_type, input_value=None, 
input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
```

### dstack version

master
