### ISSUE TITLE
[Feature]: Allow to configure VPCs via their IDs rather than name

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1156]
### Problem

Often VPCs have no name configured and can be only referenced by their ID. Also, in most cases, ML engineers don't have permission to change the names of VPCs.

### Solution

Allow to configure VPCs by their IDs for every region.

### Would you like to help us implement this feature by sending a PR?

No

**Comment by r4victor** [comment]
I can suggest the following configuration format:

```
- type: aws
  ...
  vpc_ids:
    us-east-1: vpc-0a2b3c4d5e6f7g8h
    us-east-2: vpc-9i8h7g6f5e4d3c2b
    us-west-1: vpc-4d3c2b1a0f9e8d7
    us-west-2: vpc-6f5e4d3c2b1a09i
    ap-southeast-1: vpc-8h7g6f5e4d3c2b1
    ca-central-1: vpc-3c2b1a09i8h7g6f
    eu-central-1: vpc-5e4d3c2b1a09i8h
    eu-west-1: vpc-2b1a09i8h7g6f5e4
    eu-west-2: vpc-1a09i8h7g6f5e4d3
    eu-west-3: vpc-9i8h7g6f5e4d3c2b
    eu-north-1: vpc-7g6f5e4d3c2b1a09
```

Users will be able to configure either `vpc_name` or `vpc_ids`. `vpc_ids` have to be specified for all configured regions.
