### ISSUE TITLE
When running locally, the command `dstack run` exits before the workflow is marked as `Done`

### ISSUE THREAD

**Issue by kengz** [dstackai/dstack#116]
source repo: https://github.com/kengz/mnist-classifier

workflow file
```yaml
workflows:
  - name: pip-download
    help: (pip demo-only) Download the MNIST dataset
    provider: bash
    commands:
      - pip install -r requirements.txt
      - python -m mnist.prepare_data
    artifacts:
      - path: data
    resources:
      local: true

  - name: pip-train
    help: (pip demo-only) Train an MNIST model
    deps:
      - workflow: pip-download
    provider: bash
    commands:
      - pip install -r requirements.txt
      - python -m mnist.train
    artifacts:
      - path: lightning_logs
    resources:
      local: true
```

command:
```bash
# this runs ok
➜ dstack run pip-download
Downloading runner: 100%|██████████████████| 51.6M/51.6M [00:07<00:00, 7.12MB/s]
 RUN               WORKFLOW        STATUS   A…  ARTIFACTS          SUBMITT…  T…
 nice-grasshoppe…  pip-download    Submit…      data               11 sec …

Provisioning... It may take up to a minute. ✓

To interrupt, press Ctrl+C.
...

100%|██████████| 4542/4542 [00:00<00:00, 3047109.53it/s]
Extracting /workflow/data/MNIST/raw/t10k-labels-idx1-ubyte.gz to /workflow/data/MNIST/raw

# then, running this gives error
➜ dstack run pip-train
Cannot find any successful workflow with the name 'pip-download' in the 'kengz/mnist-classifier' repo
```

`dstack ps -a` shows the pip-download indeed finished successfully:
```bash
dstack ps -a
...
 nice-grasshopper-1  pip-download    Done                     data               6 mins ago
```
