### ISSUE TITLE
The property `before_run` didn't work for the `code` provider

### ISSUE THREAD

**Issue by radao** [dstackai/dstack#117]
It would be nice to be able to run commands for non-bash providers, like if you want to run vs code and install the requirements for the repo on startup:
```yaml
  - name: ide
    provider: code
    deps:
      - workflow: download
    commands:
      - pip install -r requirements.txt 
```

**Comment by peterschmidt85** [comment]
@radao Thanks a lot for reporting! BTW, can you try this if it works? 

```
 - name: ide
    provider: code
    deps:
      - workflow: download
    before_run:
      - pip install -r requirements.txt 
```
