### ISSUE TITLE
[Bug]: No such profile

### ISSUE THREAD

**Issue by andrewssobral** [dstackai/dstack#1177]
### Steps to reproduce

dstack run . --profile ~/.dstack/profiles.yml -f examples/.dstack.yml

### Actual behaviour

```
➜  dstack git:(master) dstack run . --profile ~/.dstack/profiles.yml -f examples/.dstack.yml 
No such profile: /Users/andrewssobral/.dstack/profiles.yml
```

### dstack version

0.18.0

### Additional information

```
dstack git:(master) cat  ~/.dstack/profiles.yml
# https://dstack.ai/docs/reference/profiles.yml/
profiles:
  - name: profile01
    spot_policy: on-demand # (Optional) The spot policy. Supports `spot`, `on-demand`, and `auto`.
    max_price: 0.5 # (Optional) The maximum price per instance per hour
    max_duration: 1h # (Optional) The maximum duration of the run.
    # retry:
    #   retry-duration: 3h # (Optional) To wait for capacity
    # backends: [azure, lambda]  # (Optional) Use only listed backends 
    default: true # (Optional) Activate the profile by default
```

```
dstack git:(master) cat examples/.dstack.yml
type: dev-environment
# This configuration launches a blank dev environment

python: "3.11"

ide: vscode%
```
