### ISSUE TITLE
Allow workflow containers execute files from artifacts

### ISSUE THREAD

**Issue by kengz** [dstackai/dstack#124]
Currently, if your workflow tries to run any files from `deps`, you'll get `Permission defined`.
This happens because the download artifacts only have `read` and `write` permissions but not `execute` permission.
This is problematic when you want to reuse Conda environments as artifacts.

To fix this, let's by default allow the workflow container to execute any files from artifacts.

### Steps to reproduce:

Clone the `dstack` branch of https://github.com/kengz/mnist-classifier/tree/dstack

Workflows:

```yaml
workflows:
    - name: setup-conda
    help: setup Conda env as artifact for reuse by mounting
    provider: bash
    commands:
      - conda env create --file environment.yml
    artifacts:
      - path: /opt/conda/envs/mnist

  - name: test-conda
    help: Test Conda reuse
    provider: bash
    deps:
      - workflow: setup-conda
    commands:
      - conda env list
      - conda activate mnist
```

steps to reproduce:

1. `dstack run setup-conda` 

```shell
dstack ps
 RUN         WORKFLOW      SUBMITTED    OWNER  STATUS  TAG 
 rare-eel-1  create-conda  26 mins ago  kengz  Done  
```

2. `dstack run test-conda`

```shell
dstack run test-conda 

 RUN          WORKFLOW    SUBMITTED  OWNER  STATUS     TAG 
 tall-crab-1  test-conda  now        kengz  Submitted      

Provisioning... It may take up to a minute. ✓

To interrupt, press Ctrl+C.

# conda environments:
#
base                     /opt/conda
3.10                  *  /opt/conda/envs/3.10
mnist                    /opt/conda/envs/mnist

bash: /opt/conda/envs/mnist/bin/python: Permission denied
Connection to remote host was lost.
```
