### ISSUE TITLE
[Bug]: Private registry_auth does not seem to be respected for Runpod deployments

### ISSUE THREAD

**Issue by dinosaursarecool** [dstackai/dstack#1297]
### Steps to reproduce

1. example dstack configuration, `example.dstack.yml`:
```
type: task

image: <private docker hub repo>/example:latest
registry_auth:
  username: <private docker hub username>
  password: <private docker hub password/token>

backends: [runpod]
```

2. `dstack run . -f example.dstack.yml` works and starts provisioning
3. The pod is created in Runpod as expected
4. The pod fails to pull the referenced image with ` pull access denied for <projectname>, repository does not exist or may require 'docker login' `

### Actual behaviour

Screenshot of logs from runpod:
![image](https://github.com/dstackai/dstack/assets/1682084/c4966fa4-26eb-4a4f-807c-8d9d9f97053f)

### dstack version

0.18.2
