### ISSUE TITLE
Support provisioning instances without public IPs on GCP

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#1321]
Similar to AWS, GCP backend config should support `public_ips: true/false` property:

```
type: gcp
  creds:
    type: default
  public_ips: false
```

To provision an instance without public IP in GCP, the instance should have no access config.

The user is expected to set up [Cloud NAT](https://cloud.google.com/nat/docs/overview) that enables instances without public IPs to access the internet. dstack should probably check if Cloud NAT is set up.
