### ISSUE TITLE
Introduce Fleets for cluster provisioning and management

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#1327]
Currently, dstack provides the `dstack pool add` command to provision cloud instances and the `dstack pool add-ssh` command to add on-prem instances via ssh. This interface has several limitations. The major one is that there is no way to provision/add clusters. Managing clusters via pools is also not optimal.

The proposal is to introduce **fleets** for provisioning and managing instances and clusters of instances. Fleets are to be provisioned with `dstack apply`. Here's what `fleet` configuration will look like:

```
# cloud fleet
type: fleet
name: my-fleet
nodes: 4
placement: cluster/any
resources:
# ... all profile params
```

```
# ssh fleet
type: fleet
name: my-ssh-fleet
ssh:
  user: ubuntu
  ssh_key: ~/.ssh/key.pem
  port: 22
  network: "1.0.0.0/24"
  hosts:
    - "1.1.1.1"
    - "2.2.2.2"
    - hostname: "3.3.3.3"
      user: different-user
    - hostname: "4.4.4.4"
      ssh_key: ~/.ssh/different-key.pem
```
