### ISSUE TITLE
Request ID wasn't specified in `runner.yaml` resulting in the EC2 instance not terminated properly

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#138]
Run name: `cowardly-elephant-1`
Runner ID: `d0d8192a28be4ff4853307b6193f2df3`

`runner.yaml` from S3:

```yaml
job:
  apps: []
  artifacts:
  - mount: false
    path: checkpoints
  - mount: false
    path: /root/.cache/huggingface/hub
  commands:
  - conda install psutil orjson -y
  - pip install -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
  - pip install -e git+https://github.com/openai/CLIP.git@main#egg=clip
  - pip install -e git+https://github.com/peterschmidt85/stable_diffusion_inference@main#egg=sd_inference
  - python stability_diffusion/download.py
  deps: []
  env: {}
  host_name: ''
  image_name: dstackai/miniforge:3.9
  job_id: cowardly-elephant-1,sd-checkpoints,0
  local_repo_user_email: andrey.cheptsov@gmail.com
  local_repo_user_name: peterschmidt85
  master_job_id: ''
  port_count: 0
  ports: []
  provider_name: bash
  repo_branch: main
  repo_diff: "diff --git a/.dstack/workflows/stability_diffusion.yaml b/.dstack/workflows/stability_diffusion.yaml\n\
    index 8168b93..92b0b44 100644\n--- a/.dstack/workflows/stability_diffusion.yaml\n\
    +++ b/.dstack/workflows/stability_diffusion.yaml\n@@ -18,14 +18,25 @@ workflows:\n\
    \     help: \"This workflow generates images using the model checkpoints from\
    \ the `sd-checkpoints` workflow\"\n     provider: bash\n     deps:\n-      - workflow:\
    \ sd-checkpoints\n+      - tag: sd-checkpoints\n     commands:\n       - conda\
    \ install psutil orjson -y\n       - pip install -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers\n\
    -        pip install -e git+https://github.com/openai/CLIP.git@main#egg=clip\n\
    +      - pip install -e git+https://github.com/openai/CLIP.git@main#egg=clip\n\
    \       - pip install -e git+https://github.com/peterschmidt85/stable_diffusion_inference@main#egg=sd_inference\n\
    +      - find .\n       - python stability_diffusion/generate.py ${{ run.args\
    \ }}\n     artifacts:\n       - path: ./output\n     resources:\n-      memory:\
    \ 16GB\n+#      memory: 16GB\n+\n+  - name: sd-test\n+    provider: code\n+  \
    \  deps:\n+      - workflow: sd-checkpoints\n+    run_before:\n+      - conda\
    \ install psutil orjson -y\n+      - pip install -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers\n\
    +      - pip install -e git+https://github.com/openai/CLIP.git@main#egg=clip\n\
    +      - pip install -e git+https://github.com/peterschmidt85/stable_diffusion_inference@main#egg=sd_inference\n\
    diff --git a/.vscode/launch.json b/.vscode/launch.json\nnew file mode 100644\n\
    index 0000000..3d70f96\n--- /dev/null\n+++ b/.vscode/launch.json\n@@ -0,0 +1,17\
    \ @@\n+{\n+  \"version\": \"0.2.0\",\n+  \"configurations\": [\n+    {\n+    \
    \  \"name\": \"Stability Diffusion: Generate\",\n+      \"type\": \"python\",\n\
    +      \"request\": \"launch\",\n+      \"program\": \"stability_diffusion/generate.py\"\
    ,\n+      \"args\": [\n+        \"-P\",\n+        \"mouse\"\n+      ],\n+    \
    \  \"console\": \"integratedTerminal\",\n+      \"justMyCode\": false\n+    }\n\
    +  ]\n+}\n\\ No newline at end of file\ndiff --git a/stability_diffusion/generate.py\
    \ b/stability_diffusion/generate.py\nindex 0c5edd4..2459d25 100644\n--- a/stability_diffusion/generate.py\n\
    +++ b/stability_diffusion/generate.py\n@@ -1,5 +1,4 @@\n import argparse\n-import\
    \ os\n from pathlib import Path\n \n from stable_diffusion_inference import create_text2image\n\
    @@ -9,10 +8,12 @@ if __name__ == '__main__':\n     parser.add_argument(\"-v\"\
    , \"--variant\", choices=[\"sd1\", \"sd2_base\", \"sd2_high\"], default=\"sd1\"\
    )\n     parser.add_argument(\"-S\", \"--size\", type=int, default=512)\n     parser.add_argument(\"\
    -s\", \"--steps\", type=int, default=1)\n-    parser.add_argument(\"-p\", \"--prompt\"\
    , action='append', required=True)\n+    parser.add_argument(\"-P\", \"--prompt\"\
    , action='append', required=True)\n     args = parser.parse_args()\n     text2image\
    \ = create_text2image(args.variant, cache_dir=\"checkpoints\")\n-    image = text2image(args.prompt,\
    \ args.size, args.steps)\n+    response = text2image(args.prompt, args.size, args.steps)\n\
    +    images = response if isinstance(response, list) else [response]\n     output_path\
    \ = Path(\"output\")\n     output_path.mkdir(parents=True, exist_ok=True)\n- \
    \   image.save(output_path / f\"{(os.environ.get('RUN_NAME') or 'image')}.png\"\
    )\n+    for i in range(len(images)):\n+        images[i].save(output_path / f\"\
    {i}.png\")"
  repo_hash: f8c6f1128985acd7257bf6e0273344225561d5b5
  repo_host_name: github.com
  repo_name: dstack-examples
  repo_port: 0
  repo_user_name: dstackai
  request_id: ''
  requirements:
    memory_mib: 15258
  run_name: cowardly-elephant-1
  runner_id: d0d8192a28be4ff4853307b6193f2df3
  status: submitted
  submitted_at: 1670612995673
  tag_name: sd-checkpoints
  workflow_name: sd-checkpoints
  working_dir: ''
request_id: null
resources:
  cpus: 4
  gpus: []
  interruptible: false
  local: false
  memory_mib: 16384
runner_id: d0d8192a28be4ff4853307b6193f2df3
```

EC2 system log: 

```
ip-172-31-31-195 login: 

[  307.208779] cloud-init[1286]: time=2022-12-09T19:15:18Z level=error msg=Failed run err=[executor.go:255 executor.(*Executor).runJob] [executor.go:462 executor.(*Executor).processJob] [executor.go:455 executor.(*Executor).processJob.func1] [engine.go:209 container.(*DockerRuntime).Wait] container exited with exit code: 1
[  307.296226] cloud-init[1286]: time=2022-12-09T19:15:18Z level=error msg=dstack-runner ended with an error:
[  309.001100] cloud-init[1286]: time=2022-12-09T19:15:20Z level=error msg=Shutdown err=[ec2.go:60 s3.(*ClientEC2).TerminateInstance] operation error EC2: TerminateInstances, https response error StatusCode: 400, RequestID: d5adbb43-99d7-4495-8229-3112bb315138, api error InvalidInstanceID.Malformed: Invalid id: "" (expecting "i-...")
```
