### ISSUE TITLE
Document how to reduce cold start times for services using fleets and volumes

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#1459]
Provisioning replicas for LLM inference can take significant time (image pull + model download). dstack now has two features that help solve this problem. Fleets allow keeping machines with pulled images. And volumes allow persisting model files across runs.

Here's an example of how to scale LLM replicas without cold start times via dstack:

1. Create a multi-attach volume (currently, only volumes that can be attach to multiple instances are supported only for runpod).

2. Run a service:

```
type: service

image: ghcr.io/huggingface/text-generation-inference:sha-3905f85
env:
  - HUGGING_FACE_HUB_TOKEN
  - MODEL_ID=mistralai/Mistral-7B-Instruct-v0.2
port: 80
commands:
  - text-generation-launcher --port 80 --trust-remote-code

backends: [runpod]
resources:
  gpu: 24GB

replicas: 1..2
scaling:
  metric: rps
  target: 30

model:
  format: tgi
  type: chat
  name: mistralai/Mistral-7B-Instruct-v0.2

volumes:
 - name: my-runpod-volume
   path: /data # TGI stores model in /data

```

The first replica takes the full time to start up. After that, upscaling new replicas or restarting service takes seconds: a) runpod caches the docker image b) model downloading is skipped since it's present on the volume:

```
2024-07-26T09:55:32.927639Z  INFO download: text_generation_launcher: Starting check and download process for mistralai/Mistral-7B-Instruct-v0.2
2024-07-26T09:55:35.042076Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.
2024-07-26T09:55:35.642019Z  INFO download: text_generation_launcher: Successfully downloaded weights for mistralai/Mistral-7B-Instruct-v0.2
```

This is a cool feature of dstack that should be documented. We should also improve it further:

* Support multi-attach volumes for AWS, GCP, and other backends. Multi-attach volumes allow reusing the same volume for all replicas (within a region). An alternative is to use a volume per replica, which can be inconvenient to manage and specify. 
* Solving long pulling times with fleets (for VM backends) may not be desirable since users may not want to pay for idle GPUs. See if there are other viable solutions. (It seems like one needs to keep GPU at hand anyway since it'll take some time to provision).
