### ISSUE TITLE
Support GitHub commands syntax

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1496]
GitHub offers a very convenient syntax for commands:

```yaml
jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Group of log lines
        run: |
            echo "::group::My title"
            echo "Inside group"
            echo "::endgroup::"
```

It would be great to have it also supported for dstack's commands. Example:

```yaml
type: dev-environment
init: |
    conda install cuda
    pip install flash-attn --no-build-isolation
    git clone https://github.com/huggingface/alignment-handbook.git
    cd alignment-handbook
    pip install .
    pip install wandb
````

Reasons:
1. Using dash may be sometimes inconvenient, esp. when you have many lines and sometimes want to copy and paste commands
2. GitHib syntax is very familiar

_P.S.: Note, this is just a minor cosmetics enhancement_
