### ISSUE TITLE
[Feature]: Support env interpolation in YAML

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1539]
Example:

```
type: dev-environment
name: train

image: dstackai/base:py3.10-0.4-cuda-12.1
registry_auth:
  username: ${{ env.DOCKER_USER }}
  password: ${{ env.DOCKER_USERPASSWORD }}
```
