### ISSUE TITLE
[UX] Support a shorter syntax for model mapping

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1590]
Currently, I have to specify:

```
model:
  type: chat
  name: meta-llama/Meta-Llama-3.1-70B-Instruct
  format: openai
```

I suggest that we allow to specify

```
model: meta-llama/Meta-Llama-3.1-70B-Instruct
```

In that case `type` and `format` will use the default values.
