### ISSUE TITLE
Installing additional extensions for `code` provider

### ISSUE THREAD

**Issue by radao** [dstackai/dstack#160]
Is it possible to install additional extensions for the `code` provider? I was looking for a way to do this using `before_run` but don't see the `code` cli on the path. Also is it possible to provide a custom docker image to use with the `code` provider?

**Comment by peterschmidt85** [comment]
@radao Yes, it should be possible to install additional extensions.

##  Installing code extensions

Here's an example of how to install extensions:

```yaml
workflows:
  - name: ide-code
    provider: code
    before_run:
      - /tmp/openvscode-server-v1.72.3-linux-arm64/bin/openvscode-server --install-extension eamodio.gitlens
 ```

> **NOTE:**
> Currently, the default version is `1.72.3` but it may change in the future.
>
> Here's the list of the upcoming changes in `dstack 0.1` (planned for the next week):
> 1. The `before_run` will be renamed to `setup`
> 2. We'll introduce the `version` property for the `code` provider that will allow you to pin the version of `code`
>
> We'll make the corresponding announcement.

## Custom Docker image

Would you be open to discussing this issue over a chat? Technically, we can implement it, but I'd love to discuss in a bit more detail how it should work. If possible ping me (Andrey) in [dstack's Slack](https://join.slack.com/t/dstackai/shared_invite/zt-xdnsytie-D4qU9BvJP8vkbkHXdi6clQ).
