### ISSUE TITLE
[Bug]: Reversed run logs order in the dstack web interface when CloudWatch Logs are used

### ISSUE THREAD

**Issue by un-def** [dstackai/dstack#1611]
### Steps to reproduce

1. Configure dstack to use CloudWatch Logs (not reproducible with the file-based log storage).
2. Run a task producing log events:
    ```yaml
    type: task
    image: debian:bookworm
    commands:
      - c=1; while true; do echo $c; c=$((c+1)); sleep .05; done 
    ````
3. Check logs in the dstack web interface `https://dstack.example.com/projects/main/runs/{run_name}`

### Actual behaviour

Logs are displayed in reversed order:

![image](https://github.com/user-attachments/assets/65e8b26b-aa84-4ea1-89ef-5ac41ad7d122)

### Expected behaviour

Logs are displayed in chronological order, from earliest to latest.

### dstack version

0.18.11
