### ISSUE TITLE
`dstack ls` shows incorrect subdirectories  paths for local runs

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#168]
Run a local workflow that writes artifacts in subdirectories, e.g.:
```
workflows:
  - name: hello
    provider: bash
    commands:
      - echo "Hello, world!" > output/hello.txt
      - echo "Hello, world!2" > output/hello2.txt
      - mkdir output/subdir/
      - echo "Hello, world!3" > output/subdir/hello3.txt
    artifacts:
      - path: output
```
`dstack ls brown-termite-0` shows:
```
 ARTIFACT  FILE        SIZE   BACKENDS 
 output    hello2.txt  15.0B  local    
           hello.txt   14.0B  local    
 subdir    hello3.txt  15.0B  local 
```
The correct output (from remote run) is:
```
 ARTIFACT  FILE               SIZE   BACKENDS 
 output    hello.txt          14.0B  aws      
           hello2.txt         15.0B  aws      
           subdir/hello3.txt  15.0B  aws 
```
