### ISSUE TITLE
[Bug]: Task Fails with Error Code INTERRUPTED_BY_NO_CAPACITY

### ISSUE THREAD

**Issue by movchan74** [dstackai/dstack#1738]
### Steps to reproduce

1. Clone repo: https://github.com/mobiusml/aana_sdk.git
2. Install dstack: `pip install dstack`
3. Configure dstack: 
   ```bash
   dstack config --url https://sky.dstack.ai --project <project_name> --token <token>
   ```
4. (Optional) Modify `tests.dstack.yml` to disable volume and GPU tests for faster runs:
   ```yaml
   type: task
   name: aana-tests
   backends: [runpod]
   image: nvidia/cuda:12.1.0-cudnn8-devel-ubuntu22.04
   env:
     - HF_TOKEN
   commands:
     - apt-get update
     - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
     - apt-get install -y libgl1 libglib2.0-0 ffmpeg python3 python3-dev postgresql sudo
     - locale-gen en_US.UTF-8
     - export LANG="en_US.UTF-8" LANGUAGE="en_US:en" LC_ALL="en_US.UTF-8"
     - curl -sSL https://install.python-poetry.org | python3 -
     - export PATH=$PATH:/root/.local/bin
     - poetry install
     - HF_HUB_CACHE="/models_cache" CUDA_VISIBLE_DEVICES="" poetry run pytest -vv
   max_price: 1.0
   resources:
     cpu: 9..
     memory: 32GB..
     gpu: 40GB..
   ```

5. Initialize dstack: `dstack init`
6. Start the test run: `HF_TOKEN="" dstack apply -f tests.dstack.yml`

At the end of the run, you will see the following error message:

```
Run failed with error code INTERRUPTED_BY_NO_CAPACITY.
```

### Actual behaviour

The test runs successfully, and all tests pass, but the task fails at the end with the error `INTERRUPTED_BY_NO_CAPACITY`. This occurs regardless of whether the tests pass or fail, which causes the GitHub Actions workflow to be marked as failed even though the tests are successful.

Sample error log:

```
aana/tests/units/test_whisper_params.py::test_whisper_params_invalid_temperature[temperature1] PASSED [ 98%]
aana/tests/units/test_whisper_params.py::test_whisper_params_invalid_temperature[invalid_temperature] PASSED [ 99%]
aana/tests/units/test_whisper_params.py::test_whisper_params_invalid_temperature[2] PASSED [100%]

=============================== warnings summary ===============================
../root/.cache/pypoetry/virtualenvs/aana-M5oJUcis-py3.10/lib/python3.10/site-packages/pyannote/core/notebook.py:134
  /root/.cache/pypoetry/virtualenvs/aana-M5oJUcis-py3.10/lib/python3.10/site-packages/pyannote/core/notebook.py:134: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
    cm = get_cmap("Set1")

../root/.cache/pypoetry/virtualenvs/aana-M5oJUcis-py3.10/lib/python3.10/site-packages/pkg_resources/__init__.py:3154
../root/.cache/pypoetry/virtualenvs/aana-M5oJUcis-py3.10/lib/python3.10/site-packages/pkg_resources/__init__.py:3154
../root/.cache/pypoetry/virtualenvs/aana-M5oJUcis-py3.10/lib/python3.10/site-packages/pkg_resources/__init__.py:3154
../root/.cache/pypoetry/virtualenvs/aana-M5oJUcis-py3.10/lib/python3.10/site-packages/pkg_resources/__init__.py:3154
../root/.cache/pypoetry/virtualenvs/aana-M5oJUcis-py3.10/lib/python3.10/site-packages/pkg_resources/__init__.py:3154
  /root/.cache/pypoetry/virtualenvs/aana-M5oJUcis-py3.10/lib/python3.10/site-packages/pkg_resources/__init__.py:3154: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('pyannote')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

aana/tests/db/datastore/test_caption_repo.py: 24 warnings
aana/tests/db/datastore/test_task_repo.py: 14 warnings
aana/tests/db/datastore/test_transcript_repo.py: 6 warnings
aana/tests/db/datastore/test_video_repo.py: 18 warnings
  /workflow/aana/storage/repository/base.py:59: LegacyAPIWarning: The Query.get() method is considered legacy as of the 1.x series of SQLAlchemy and becomes a legacy construct in 2.0. The method is now available as Session.get() (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
    entity: T | None = self.session.query(self.model_class).get(item_id)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========== 177 passed, 16 skipped, 68 warnings in 420.58s (0:07:00) ===========
Run failed with error code INTERRUPTED_BY_NO_CAPACITY.
Check CLI, server, and run logs for more details.
```

### Expected behaviour

The task should be completed successfully if all the tests pass without encountering the `INTERRUPTED_BY_NO_CAPACITY` error. The GitHub Actions workflow should also reflect the successful test run without marking the task as failed due to the capacity error.be completed

### dstack version

0.18.15

### Server logs

```shell
Used dstack Sky with my own API keys.
```

### Additional information

- GitHub Action workflow that I'm using to run that automatically:: https://github.com/mobiusml/aana_sdk/blob/main/.github/workflows/run_tests_with_gpu.yml
- Example run that should have succeeded but failed due to the error: https://github.com/mobiusml/aana_sdk/actions/runs/11072757163/job/30767721883
- Logs from a run showing the error:

```
2024-09-27T15:18:29.4505488Z ================ 189 passed, 68 warnings in 1395.60s (0:23:15) =================
2024-09-27T15:18:48.3599503Z Run failed with error code INTERRUPTED_BY_NO_CAPACITY.
2024-09-27T15:18:48.3600357Z Check CLI, server, and run logs for more details.
2024-09-27T15:18:48.4605321Z ##[error]Process completed with exit code 1.
2024-09-27T15:18:48.4690032Z Post job cleanup.
```
