### ISSUE TITLE
`dstack run` fails after `dstack init` is called without proper credentials

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#175]
Steps to reproduce:

1. Create a private repo
2. Run `dstack init` without any credentials.
3. Run a simple workflow:
```
workflows:
  - name: hello
    provider: bash
    commands:
      - echo Done

```
It will exit silently with status as `failed`.

The issue is fixied if you supply the credentials as `dstack init -t my_github_token`.

`dstack init` should check if the credentials are set up properly. At the moment, it performs the check by running `git ls-remote` but it's succesfull because git takes the token from `gitcredentials` – e.g. keychain on MacOS.
