### ISSUE TITLE
[Bug]: `dstack attach --logs` sometimes displays logs from another attach, and vice versa

### ISSUE THREAD

**Issue by un-def** [dstackai/dstack#1814]
### Steps to reproduce

task configuration:

```yaml
type: task
name: attach-bug

nodes: 2

commands:
  - echo DSTACK_NODE_RANK=$DSTACK_NODE_RANK
  - sleep 60
```

1. Apply the configuration: `dstack apply -f attach-bug.task.dstack.yml`.
2. While the run is still provisioning, attach to the second job: `dstack attach --logs attach-bug --job 1`.

### Actual behaviour

![image](https://github.com/user-attachments/assets/6dbb446a-502c-4c90-924a-59a7b9359554)

or

![image](https://github.com/user-attachments/assets/0374b7f9-6b67-411b-ab52-3f6715c8c7f2)

### dstack version

0.18.17
