### ISSUE TITLE
[Bug]: Unexpected dstack server error when commands are not specified

### ISSUE THREAD

**Issue by deep-diver** [dstackai/dstack#1828]
### Steps to reproduce

I am following the NVIDIA's official NIM tutorial ( [LINK](https://docs.nvidia.com/nim/large-language-models/latest/getting-started.html#option-2-from-ngc) ), and I am using dstack Sky.

1. Generate API Key by following [this step](https://docs.nvidia.com/nim/large-language-models/latest/getting-started.html#id1)

2. Write a `nim.dstack.yml`

```yml
type: service

image: nvcr.io/nim/meta/llama3-8b-instruct:latest
env:
  - NGC_API_KEY
registry_auth:
  username: "$oauthtoken"
  password: $NGC_API_KEY

port: 8000

spot_policy: auto
resources:
  gpu: 48GB
  disk: 300GB..
```

3. Apply `nim.dstack.yml`

```bash
$ dstack apply -f nim.dstack.yml
```

### Actual behaviour

```bash
Unexpected dstack server error
```

### Expected behaviour

I should start provisioning

### dstack version

0.18.17

### Additional information

when specifying any commands under `commands`, the provisioning process starts.
However, it takes forever and outputs the following error eventually.

```bash
All provisioning attempts failed. This is likely due to cloud providers not having enough capacity. Check CLI and server logs for more details.
```

**Comment by jvstme** [comment]
### Workaround

Add `commands` to the run configuration.
Also avoid using RunPod and Vast.ai for running NIM or other non-root docker images until #1535 is fixed.

A working configuration:
```yaml
type: service

image: nvcr.io/nim/meta/llama3-8b-instruct:latest
env:
  - NGC_API_KEY
registry_auth:
  username: $oauthtoken
  password: ${{ env.NGC_API_KEY }}
commands:
  - /opt/nvidia/nvidia_entrypoint.sh /opt/nim/start-server.sh

port: 8000

backends: ["aws", "azure", "cudo", "datacrunch", "gcp", "lambda", "oci", "tensordock"]

spot_policy: auto
resources:
  gpu: 48GB
  disk: 300GB..
```
