### ISSUE TITLE
[Feature] Allow to configure configure tags per backend and or per configuration

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1838]
Similar to [Terraform's tags](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/resource-tagging), it should be possible to configure tags per backend and or per configuration. These tags should be assigned to any corresponding cloud resources (where it's supported).

Examples:

```
projects:
  - name: main
    backends:
      - type: was
        creds:
          type: default
        tags:
          my_app_name: dstack
          my_department: 12345
          my_environment: production
          owner: andrey@dstack.ai
          my_project: "${{ project_name }}"
          my_user: "${{ user_name }}"
```
