### ISSUE TITLE
[Bug]: Cannot specifying `public_ips` when configuring GCP via the UI

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#1839]
### Steps to reproduce

1. Configure GCP backend via the UI with `public_ips` specified

```
type: gcp
project_id: ...
vpc_name: ...
public_ips: false
creds:
  type: service_account
  filename: ...
  data: "..."
```

2. The backend won't accept the config

### dstack version

master
