### ISSUE TITLE
[Bug]: DinD doesn't allow setting memory or CPU limits

### ISSUE THREAD

**Issue by mtaran** [dstackai/dstack#1854]
### Steps to reproduce

1. make a `repro.dstack.yml` with:
```yaml
type: task
name: my-repro-task
image: dstackai/dind:latest
privileged: true
commands:
  - start-dockerd
  - sleep infinity
resources:
  cpu: 4..
  memory: 6GB..
```
2. `dstack apply -f repro.dstack.yml -y`
3. in another terminal: `dstack attach my-repro-task`
4. in yet another terminal: `ssh my-repro-task`
5. in the ssh session, try to run `docker run --rm --cpus=1 hello-world` or `docker run --rm --memory=1gb hello-world`

### Actual behaviour

```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: unable to apply cgroup configuration: cannot enter cgroupv2 "/sys/fs/cgroup/docker" with domain controllers -- it is in threaded mode: unknown.
```

### Expected behaviour

Container runs and is limited in the amount of memory/CPUs it can use.

### dstack version

0.18.18

### Additional information

Googled for the error message and it seems like there should be some way to do this, e.g. some stackoverflow links pointed to https://github.com/earthly/earthly/pull/3203

**Comment by un-def** [comment]
With [dstackai/dind:24.04-20240827003913-1](https://hub.docker.com/layers/dstackai/dind/24.04-20240827003913-1/images/sha256-a76eb5b45724ae5707983010fdb61290e75f7205ef6d9cf25939f812111441d6):

```yaml
type: task

image: dstackai/dind
privileged: true

commands:
  - start-dockerd >/dev/null 2>&1
  - docker pull ubuntu >/dev/null 2>&1
  - docker run --name sysbench ubuntu bash -c '
      export DEBIAN_FRONTEND=noninteractive &&
      apt-get update &&
      apt-get install -y sysbench
    ' >/dev/null 2>&1
  - docker commit sysbench sysbench >/dev/null 2>&1
  - docker run --rm sysbench
      bash -c 'sysbench cpu run | grep -A 1 "CPU speed"'
  - docker run --rm --cpus 0.1 sysbench
      bash -c 'sysbench cpu run | grep -A 1 "CPU speed"'
```

```shell
$ dstack apply -y -f dind-limits.task.dstack.yml
[...]
big-goose-1 provisioning completed (running)
CPU speed:
    events per second:  5200.95
CPU speed:
    events per second:   272.37
Done
```
