### ISSUE TITLE
[Feature]: Generate Docker registry password using AWS creds

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1868]
### Problem

In order to use private Docker images hosted with AWS ECR, one has to [generate](https://docs.aws.amazon.com/AmazonECR/latest/userguide/registry_auth.html) a temporarily password using `aws ecr get-login-password` and then hardcode them in the YAML file. 

### Solution

Allow `dstack` generate a temporarily password automatically on behalf of the user:

```
type: dev-environment
name: vscode    

image: 540292141660.dkr.ecr.eu-west-1.amazonaws.com/hello-world:latest
registry_auth:
  type: aws
  creds:
     type: default
ide: vscode
```

> [!WARNING]
> Note, this should work regardless of which backend the job is being running on.

> [!NOTE]
> In theory, a similar approach could be used with other clouds: [GCP](https://cloud.google.com/artifact-registry/docs/docker/pushing-and-pulling), [Azure](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-authentication?tabs=azure-cli), etc.

### Would you like to help us implement this feature by sending a PR?

No

**Comment by jvstme** [comment]
It is already possible to avoid hardcoding ECR passwords using secrets, as well as set up password renewal using external automation.

1. Set up a script to run once every 12 hours (the validity period of ECR passwords) and save a new ECR password to `dstack` project secrets.
   ```shell
   $ dstack secret set ecr_password "$(aws ecr get-login-password --region eu-west-1)"
   ```
   For example, you can use `cron` or `dstack` [scheduled tasks](https://dstack.ai/docs/concepts/tasks/#schedule) to run the script periodically.
1. In run configurations, reference the secret in `registry_auth`.
   ```yaml
   type: dev-environment
   ide: vscode
   image: xxxxxxxxxxxx.dkr.ecr.eu-west-1.amazonaws.com/xxxx/xxxx:latest
   registry_auth:
     username: AWS
     password: ${{ secrets.ecr_password }}
   ```
