### ISSUE TITLE
[Bug]: Not possible to use OS image with NVIDIA drivers on CPU instances

### ISSUE THREAD

**Issue by un-def** [dstackai/dstack#1942]
### Steps to reproduce

*Note*: currently, only AWS backend allows to customize OS images, but the issue is not backend-specific.

1. Configure a backend to use an OS image with NVIDIA drivers with CPU instances:
    ```yaml
    projects:
      - name: main
        backends:
          - type: aws
            creds:
              type: default
            os_images:
              cpu:
                name: dstack-cuda-0.6
                owner: 142421590066 
                user: ubuntu
    ```
2. Start a run on a CPU instance:
    ```yaml
    type: dev-environment
    ide: vscode
    resources:
      gpu: 0
    ```

### Actual behaviour

```
Run failed with error code CONTAINER_EXITED_WITH_ERROR.
Error: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start
container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode
as 'legacy'
nvidia-container-cli: initialization error: nvml error: driver not loaded: unknown
Check CLI, server, and run logs for more details.
```

### dstack version

0.18.22
