### ISSUE TITLE
[Bug]: Cannot update/recreate SSH fleet

### ISSUE THREAD

**Issue by un-def** [dstackai/dstack#1952]
### Steps to reproduce

1. Create and apply an SSH fleet configuration:
    ```yaml
    type: fleet
    name: fleet-vm
    ssh_config:
      hosts:
        - hostname: 192.168.122.75
          user: debian
          identity_file: ~/.ssh/vm_debian12
    ```

    ```shell
    dstack apply -f .dstack/fleet-vm.dstack.yml
     Project        main
     User           admin
     Configuration  .dstack/fleet-vm.dstack.yml
     Type           fleet
     Fleet type     ssh
     Nodes          1
     Placement      cluster

    Fleet fleet-vm does not exist yet.
    Create the fleet? [y/n]:
    ```
2. Update and apply the configuration to add more hosts, or even apply the same exact configuration, to, for example, update the `shim` binary:

    ```yaml
    type: fleet
    name: fleet-vm
    ssh_config:
      hosts:
        # the same host
        - hostname: 192.168.122.75
          user: debian
          identity_file: ~/.ssh/vm_debian12
        # a new host
        - hostname: 192.168.122.58
          user: ubuntu
          identity_file: ~/.ssh/vm_ubuntu24_04
    ```

### Actual behaviour

```
dstack apply -f .dstack/fleet-vm.dstack.yml
Instances [192.168.122.75] are already assigned to a fleet.
```

### dstack version

`master` branch (0.18.22 with https://github.com/dstackai/dstack/pull/1938 merged)
