### ISSUE TITLE
[Bug]: dstack shows me offers but gets stuck in provisioning or submit/fail/terminating loop 

### ISSUE THREAD

**Issue by playerzer0x** [dstackai/dstack#1976]
### Steps to reproduce

1. I submit a dstack request with these configurations and successfully receive an offer from Runpod:
```
image: runpod/pytorch:2.4.0-py3.11-cuda12.4.1-devel-ubuntu22.04
max_price: '30'
name: firefly-ridge-20241107-144937
ports:
- 8080
resources:
  disk:
    size: 100
  gpu:
    count: 8
    memory: 48GB
    name: RTX6000Ada
retry:
  duration: 1h
  on_events:
  - no-capacity
spot_policy: auto
type: task
volumes:
- name: growwithdaisy3
  path: /workspace
```

2. I accept the offer
3.  The request gets stuck provisioning, or in a submitting/failed/terminating loop.

![image](https://github.com/user-attachments/assets/6108a77f-940c-459a-abad-f964f80d2262)
This is provisioning still after 2+ minutes ^

Runpod logs:
2024-11-07T23:20:52Z Status: Image is up to date for runpod/pytorch:2.4.0-py3.11-cuda12.4.1-devel-ubuntu22.04
2024-11-07T23:20:52Z error creating container: container: create: container create: Error response from daemon: layer does not exist

### Expected behaviour

The pod should provision once accepted.

### dstack version

0.18.22

**Comment by jvstme** [comment]
There are probably two different problems here.

- Problem 1 — run is stuck in provisioning. I found two cases when this can happen:
  - Case 1 — `Error response from daemon: layer does not exist` in RunPod system logs. Last Friday I managed to reproduce it a couple of times, although most of the time pods worked normally. Today I can no longer reproduce it. I assume this was either a temporary or a rare RunPod-side issue, so I'd suggest we ignore it unless it shows up again.
  - Case 2 — the pod starts normally, but dstack always gets `Connection refused` when trying to connect to it via SSH. This also happens randomly but quite often. I am reaching out to RunPod, as it seems to be an issue with exposing ports that can be reproduced without dstack.
    **UPD**: reaching out to RunPod didn't help, as the issue disappeared after some time. So this could also be a temporary or a rare RunPod-side issue.

    Note that in both  cases the run should fail after 20 minutes of provisioning. As a workaround, you can consider setting `on_events: [error]` so that dstack retries provisioning after failing, although in that case it will retry on application-specific failures too.
- Problem 2 — run is stuck in submitting/failed/terminating loop. This seems to be expected if there is no capacity in RunPod. RunPod offers shown in dstack can be a bit outdated, so sometimes dstack will show offers that are actually unavailable at the moment. In this case the run will fail to start due to no capacity, but dstack will retry bacause of `on_events: [no-capacity]`. You can adjust the `retry` policy if this is not expected.

**Comment by playerzer0x** [comment]
If it helps, I got stuck provisioning a Runpod 8x H100 `spot` instance a few minutes ago. The `on-demand` instance provisions just fine. Here's the .yml:

```
commands:
- apt update
- apt -y install nvidia-cuda-toolkit libgl1-mesa-glx unzip git
- cd ..
- cd workspace/SimpleTuner
- git checkout /bugfix/file-locking-multigpu
- python3.11 -m venv .venv
- . .venv/bin/activate
- pip install -U poetry pip
- poetry install
- apt-get install git-lfs
- huggingface-cli login --token $HUGGING_FACE_HUB_TOKEN --add-to-git-credential
- wandb login
- mkdir -p datasets
- cd datasets
- huggingface-cli download --repo-type=dataset growwithdaisy/crrllcrrllxovrtn_subjects
  --local-dir=crrllcrrllxovrtn_subjects
- cd ..
- cp -r datasets/crrllcrrllxovrtn_subjects/config_20241114_133705/* config/
- ./train.sh
- rm -r datasets/crrllcrrllxovrtn_subjects
env:
- HUGGING_FACE_HUB_TOKEN
- WANDB_API_KEY
image: runpod/pytorch:2.4.0-py3.11-cuda12.4.1-devel-ubuntu22.04
max_price: '30'
name: crrllcrrllxovrtn-subjects-20241114-1337
ports:
- 8081
resources:
  disk:
    size: 100
  gpu:
    count: 8
    memory: 80GB
    name: H100
retry:
  duration: 1h
  on_events:
  - no-capacity
spot_policy: auto
type: task
volumes:
- name: growwithdaisy1
  path: /workspace

```
