### ISSUE TITLE
[Bug]: `dstack server` is not compatible with `paramiko<3.2`

### ISSUE THREAD

**Issue by un-def** [dstackai/dstack#1982]
### Steps to reproduce

server side:
```
pip install 'dstack[all]'
```
```
pip install 'paramiko<3.2'
```
```
pip freeze | grep paramiko
paramiko==3.1.0
```
```
pip check
No broken requirements found.
```
```
dstack server
```

client side:
```
cat fleet.dstack.yml
type: fleet
name: vm-fleet
ssh_config:
  user: debian
  identity_file: ~/.ssh/vm_debian12
  hosts:
    - 192.168.122.75
```
```
cat ~/.ssh/vm_debian12.pub
ssh-rsa <KEY_CONTENT> debian@debian
```
```
dstack apply -f fleet.dstack.yml
```

### Actual behaviour

See Server logs

### dstack version

0.18.24

### Server logs

```shell
[07:26:15] INFO     dstack._internal.server.background.tasks.process_instances:217 Adding ssh instance vm-fleet-0...
           WARNING  dstack._internal.server.background.tasks.process_instances:281 Provisioning instance vm-fleet-0 could not be completed because of the error: Deploy instance raised an error: 'RSAKey' object has no attribute 'fingerprint'
```
