### ISSUE TITLE
Artifacts with absolute paths aren't handled properly

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#202]
**Environment**

- `dstack` version: [master](https://github.com/dstackai/dstack/commit/1299c2f0968b316f78e8a5b7edc805233f30c75c)
- Python version: 3.11
- OS version: macOS 12.5

**Bug description**
Artifacts with absolute paths are not being pushed and pulled.

**Steps to reproduce**
Run a local workflow with an artifact specified as absolute path:
```
workflows:
  - name: hello-txt
    provider: bash
    commands:
      - echo "Hello world" > /absoutput/hello2.txt
    artifacts:
      - path: /absoutput
```
Try to push it. Observe no uploading indicator and no files in remote storage. The same goes for pull.

**Expected behavior**

**Logs**

**Screenshots**

**Additional comments**
