### ISSUE TITLE
[Bug]: Runs fail with EXECUTOR_ERROR when using partitioned external volumes

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#2083]
### Steps to reproduce

1. Create an EBS volume in AWS directly.
2. Create one partition on it and format it (e.g. `sudo fdisk /dev/xvdf `, `sudo mkfs.ext4 /dev/xvdf1`).
3. Register the volume with dstack.
4. Submit a run with the volume mounted.
5. The run fails with error:

```
Run failed with error code EXECUTOR_ERROR.
Error: prepareVolumes error: failed to mount disk: exit status 32, output: 
mount: /dstack-volumes/dstack-aws-ext-volume: wrong fs type, bad option, bad
superblock on /dev/nvme1n1, missing codepage or helper program, or other 
error.

Check CLI, server, and run logs for more details.
```

### Actual behaviour

The error occurs because the shim assumes that the disk itself is formatted and can be mounted. But it's often the case that a disk has one or more partitions that need to be mounted. 

### Expected behaviour

If there is only one partition, dstack could detect it automatically.

If the disk has multiple partitions, I assume we should allow specifying a partition to mount in run configurations and also allow mounting multiple partitions of the same volume to different mount points. E.g.

```
type: dev-environment
ide: vscode
volumes:
  - name: dstack-aws-ext-volume
    partition: 1 # identify by a number since partition name is unknown before attach
    path: /my_volume_data1
  - name: dstack-aws-ext-volume
    partition: 2
    path: /my_volume_data2
```

### dstack version

master
