### ISSUE TITLE
[Bug]: [shim] `HOME` set to `/root` if non-root user home directory doesn't exist

### ISSUE THREAD

**Issue by un-def** [dstackai/dstack#2108]
### Steps to reproduce

1. 
    ```yaml
    type: task
    image: ubuntu
    user: ubuntu
    commands:
      - echo "HOME=${HOME}"
    ```

2. 
    ```yaml
    type: task
    image: ubuntu
    user: ubuntu
    commands:
      - echo "HOME=${HOME}"
    volumes:
      - /tmp/run-home:/home
    ```

### Actual behaviour

1.
```
HOME=/home/ubuntu
```

2.
```
HOME=/root
```

### dstack version

0.18.30
