### ISSUE TITLE
`dstack logs` inserts empty new lines for local runs

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#212]
**Environment**

- `dstack` version: [master](https://github.com/dstackai/dstack/commit/74cf43e320c62947d1e833048414de7ce4ad863c) (relevant for 0.1 as well)
- Python version: 3.11
- OS version: macOS 12.5

**Bug description**
`dstack logs` inserts empty new lines for local runs. For remote runs, there is no such problem.

**Steps to reproduce**
Run a local workflow that prints multiple lines of logs `dstack run hello `:
```
workflows:
  - name: hello
    provider: bash
    commands:
      - echo 123
      - echo 456
      - echo 789
```
Then run `dstack logs {run_name}` and observe extra new lines:
```
123

456

789
```

**Expected behavior**

```
123
456
789
```

**Logs**

**Screenshots**

**Additional comments**
