### ISSUE TITLE
[Bug]: `dstack apply` on a gateway detects changes while it shouldn't

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#2161]
### Steps to reproduce

1.
```yaml
type: gateway
name: my-gateway

backend: aws
region: eu-west-1

domain: my-gateway-domain.dstack.ai
```

2. 
`dstack apply -f examples/.dstack.yml -y`

3.
`dstack apply -f examples/.dstack.yml`

### Actual behaviour

<img width="802" alt="Screenshot 2024-12-30 at 11 20 24" src="https://github.com/user-attachments/assets/a07c27ab-5d33-4565-ac1c-bb032b29f294" />

### Expected behaviour

No changes should be detected

### dstack version

0.18.33
