### ISSUE TITLE
[Bug]: Cannot attach an AWS volume on dstack Sky

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#2172]
### Steps to reproduce

1. `vol.dstack.yml`

```yaml
type: volume
name: cw1
backend: aws
region: us-east-1
size: 100GB
```

2. `dev.dstack.yml`

```yaml
type: dev-environment
name: vscode
python: "3.11"
ide: vscode
spot_policy: spot
#resources:
#  gpu: 24GB
backends: [ aws ]
regions: [ us-east-1 ]
volumes:
  - name: cw1
    path: /volume_data
```

3. `dstack apply -f vol.dstack.yml`
4. `dstack apply -f dev.dstack.yml`

### Actual behaviour

```shell
dstack apply -f dev.dstack.yml
 Project                peterschmidt85
 User                   peterschmidt85
 Configuration          dev.dstack.yml
 Type                   dev-environment
 Resources              2..xCPU, 8GB.., 100GB.. (disk)
 Max price              -
 Max duration           6h
 Spot policy            spot
 Retry policy           no
 Creation policy        reuse-or-create
 Termination policy     destroy-after-idle
 Termination idle time  5m
 Reservation

 #  BACKEND  REGION     INSTANCE   RESOURCES                    SPOT  PRICE
 1  aws      us-east-1  m5.large   2xCPU, 8GB, 100.0GB (disk)   yes   $0.033
 2  aws      us-east-1  m5.xlarge  4xCPU, 16GB, 100.0GB (disk)  yes   $0.0639
 3  aws      us-east-1  c5.xlarge  4xCPU, 8GB, 100.0GB (disk)   yes   $0.0653
    ...
 Shown 3 of 55 offers, $39.7363 max

Finished run vscode already exists.
Override the run? [y/n]: y
 NAME    BACKEND          INSTANCE  RESOURCES        RESERVATION  PRICE   STATUS  SUBMITTED  ERROR
 vscode  aws (us-east-1)  m5.large  2xCPU, 8GB,                   $0.033  failed  22:09      JOB_FAILED
                                    100.0GB (disk),                                          (EXECUTOR_ERROR)
                                    SPOT

vscode provisioning completed (failed)
Run failed with error code EXECUTOR_ERROR.
Error: prepareVolumes error: volume vol-0121b9ef655d27259 not found among block devices
Check CLI, server, and run logs for more details.
```

### dstack version

0.18.33

### Additional information

The issue is reproduced only with dstack Sky, and not reproduced with the open-source version
