### ISSUE TITLE
[Bug]:  `Could not find instance offers` with SSH fleet

### ISSUE THREAD

**Issue by un-def** [dstackai/dstack#2248]
### Steps to reproduce

```yaml
# fleet.dstack.yml
type: fleet
name: my-fleet
ssh_config:
  user: dstack
  identity_file: ~/.ssh/dstack
  hosts:
    - 192.168.200.100
```

### Actual behaviour

```
dstack apply -f fleet.dstack.yml

 Project        main
 User           admin
 Configuration  fleet.dstack.yml
 Type           fleet
 Fleet type     ssh
 Nodes          1
 Placement      any

Could not find instance offers that match your requirements. Please check the requirements table above or visit the troubleshooting guide:
https://dstack.ai/docs/guides/troubleshooting/#no-offers

Fleet my-fleet does not exist yet.
Create the fleet? [y/n]:
```

### Expected behaviour

Same, but without the warning.

### dstack version

0.18.39

### Server logs

```shell

```
