### ISSUE TITLE
[Bug]: The `resources->gpu->memory` setting is ignored 

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#226]
### dstack version

master

### Python version

3.11

### Host OS

macOS 12.5

### Host Arch

ARM

### What happened?

Run a remote workflow with the `resources->gpu->memory` setting specified:

```
workflows:
  - name: hello
    provider: bash
    commands:
      - echo Done
    resources:
      gpu:
        memory: 8GB
```

You'd expect it to run a gpu instance but it will launch the most basic instance (e.g. c5.large in case of AWS). The reason is that the `memory` setting is not parsed at all:

https://github.com/dstackai/dstack/blob/7ad54c26e66784748756f8255619082157580dc3/cli/dstack/providers/__init__.py#L408-L423
