### ISSUE TITLE
[Bug]: Finished jobs included in run price

### ISSUE THREAD

**Issue by jvstme** [dstackai/dstack#2313]
### Steps to reproduce

1. Run a service with 2 replicas.
   ```yaml
   type: service
   name: nginx
   image: nginx
   port: 80
   replicas: 2
   ```
1. Scale it down to 1 replica.
   ```yaml
   type: service
   name: nginx
   image: nginx
   port: 80
   replicas: 1
   ```
1. Open the run page in the UI.

### Actual behaviour

The run price includes the prices of both jobs, even though the second one is finished.

![Image](https://github.com/user-attachments/assets/5b00315a-8c00-4131-89ec-4cf8cdd12853)

### Expected behaviour

For unfinished runs - the run price does not include the prices of `terminated`, `aborted`, `failed`, and `done` jobs.

For finished runs - to be decided. One option is the average price (cost divided by duration).

### dstack version

0.18.42

### Server logs

```shell

```

### Additional information

The run price is calculated in the UI, so we can make a quick fix there.

But it may also make sense to move this calculation to dstack-server, considering the calculation is becoming more complicated with this issue and with the introduction of blocks.
