### ISSUE TITLE
[Bug]: UI shows incorrect job submission in run details page

### ISSUE THREAD

**Issue by jvstme** [dstackai/dstack#2314]
### Steps to reproduce

1. Run a service with 2 replicas.
   ```yaml
   type: service
   name: nginx
   image: nginx
   port: 80
   replicas: 2
   ```
1. Scale it down to 1 replica.
   ```yaml
   type: service
   name: nginx
   image: nginx
   port: 80
   replicas: 1
   ```
1. Scale it up to 2 replicas.
   ```yaml
   type: service
   name: nginx
   image: nginx
   port: 80
   replicas: 2
   ```
1. Open the run page in the UI.

### Actual behaviour

While the second job is actually running (step 3), the UI shows the details from the first submission of the job, which is terminated (step 2).

![Image](https://github.com/user-attachments/assets/0af61e28-9c40-48c2-af55-f0b5fc9de58e)

### Expected behaviour

For each job, the details of the latest job submission are shown.

### dstack version

0.18.42

### Server logs

```shell

```
