### ISSUE TITLE
[Feature] Private Docker registry support

### ISSUE THREAD

**Issue by charlienewey** [dstackai/dstack#246]
# Problem

Cannot use a private Docker registry to provide images to `dstack`

# Solution

## Implementation notes

Login details could be stored and saved using `dstack secrets`, perhaps.

I imagine it working a little like the below;

```
workflows:
  - name: my-awesome-workflow
    provider: docker
    image: my-awesome-registry.com/my-registry-name:latest
    provider_setup:
      - docker login $DOCKER_REGISTRY_HOST --username $DOCKER_REGISTRY_USERNAME --password 
$DOCKER_REGISTRY_PASSWORD
    setup:
      - pip install my-package
    commands:
      - echo "hooray"
```

# Benefits

This enables the use of private Docker images with secrets and/or proprietary code in `dstack` workflows.

**Comment by peterschmidt85** [comment]
Here's a suggestion on how to implement it:

Add the optional `auth` property for the `docker` provider which can be used to pass basic credentials. Example:

```
workflows:
  - name: my-awesome-workflow
    provider: docker
    image: my-awesome-registry.com/my-registry-name:latest
    auth:
      server: $DOCKER_REGISTRY_HOST
      username: $DOCKER_REGISTRY_USERNAME
      password: $DOCKER_REGISTRY_PASSWORD
    setup:
      - pip install my-package
    commands:
      - echo "hooray"
```

The `server` property is optional.

The user must configure secrets `DOCKER_REGISTRY_HOST`, `DOCKER_REGISTRY_USERNAME`, and `DOCKER_REGISTRY_PASSWORD`.
