### ISSUE TITLE
[Bug]: dstack metrics not showing GPU utilization with AMD Mi300x

### ISSUE THREAD

**Issue by Bihan** [dstackai/dstack#2551]
### Steps to reproduce

1. dstack apply -f hotaisle.fleet.yml
2. dstack apply -f .dstack.yml

**Configurations:**

.dstack.yml
```
type: service
name: deepseek-r1-amd

image: rocm/vllm:rocm6.3.1_instinct_vllm0.8.3_20250410
env:
  - MODEL_ID=deepseek-ai/DeepSeek-R1-Distill-Llama-70B
  - MAX_MODEL_LEN=126432
commands:
  - vllm serve $MODEL_ID
    --max-model-len $MAX_MODEL_LEN
    --trust-remote-code
port: 8000

model: deepseek-ai/DeepSeek-R1-Distill-Llama-70B

volumes:
  - /root/.cache/huggingface/hub:/root/.cache/huggingface/hub

resources:
    gpu: mi300x
    disk: 300Gb..
```
2.hotaisle.fleet.yml

```
type: fleet
# The name is optional, if not specified, generated randomly
name: hotaisle-fleet

# Uncomment if instances are interconnected
#placement: cluster

# SSH credentials for the on-prem servers
ssh_config:
  user: hotaisle
  identity_file: ~/.ssh/id_rsa
  hosts:
    - 23.183.40.75
```

### Actual behaviour

<img width="803" alt="Image" src="https://github.com/user-attachments/assets/a439666f-801e-4254-8a2f-dff2fe39d012" />

### Expected behaviour

Shows GPU Utilization Stats

### dstack version

0.19.4

### Server logs

```shell

```
