### ISSUE TITLE
[Feature]: Secure method for accessing private docker registries

### ISSUE THREAD

**Issue by colinjc** [dstackai/dstack#2555]
### Problem

Currently the only documented way of pulling images from private registries is to use the [registry_auth](https://dstack.ai/docs/reference/dstack.yml/task/#_registry_auth) fields dstack configs. This option requires putting secrets in a file that will generally be committed. 

### Would you like to help us implement this feature by sending a PR?

No

**Comment by r4victor** [comment]
@colinjc, the current recommended way is to use env interpolation for sensitive values:

```
type: service
image: ...
env:
  - REGISTRY_USERNAME
  - REGISTRY_PASSWORD
registry_auth:
  username: ${{ env.REGISTRY_USERNAME }}
  password: ${{ env.REGISTRY_PASSWORD }}
```

This way you don't need to hardcode sensitive values in files. Still, the values will be interpolated on the client side and will become a part of the run configuration. A proper solution will require #708.

@peterschmidt85, I recall registry_auth examples were using env interpolation. It should be reverted as hardcoding passwords is a no-go.
