### ISSUE TITLE
[Feature]: Specify AWS Profile Name in backend setup

### ISSUE THREAD

**Issue by oborchers** [dstackai/dstack#2560]
### Problem

Currently your readme states, that:

> There are two ways to configure AWS: using an access key or using the default credentials.

```
projects:
  - name: main
    backends:
      - type: aws
        creds:
          type: default
```

https://dstack.ai/docs/concepts/backends/

this is may not be applicable to larger AWS setups with many different environments. In a situation with Control Tower and SSO Login users will not have access keys. Nor will they have a default profile, since they need to switch context regularly.

### Solution

Provide the ability to use profile names instead.

```
projects:
  - name: main
    backends:
      - type: aws
        creds:
          type: profile
          name: (default if empty), dev, prod, playground...
```

### Would you like to help us implement this feature by sending a PR?

No
