### ISSUE TITLE
[Bug]: Doesn't allow running bash commands in background

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#257]
### dstack version

0.2

### Python version

3.9.1

### Host OS

macOS 13.1

### Host Arch

ARM

### What happened?

I want to run several bash commands inside my workflow. One of the commands must be run in background.

Here's an example:

```yaml
workflows:
  - name: test
    provider: bash
    commands:
      - echo 1 &
      - echo 2
```

The `echo 1` command must run background.

However, when I run the workflow via `dstack`, it fails:

```
bash: syntax error near unexpected token `&&'
```

### Additional Information

Background commands can be quite useful, for example, if we want to run `tensorboard` in parallel while the workflow is running.
