### ISSUE TITLE
[Bug]: "No ssh key specified for host x.x.x.x" when applying SSH fleet configuration

### ISSUE THREAD

**Issue by un-def** [dstackai/dstack#2578]
### Steps to reproduce

```yaml
type: fleet
name: fleet-vm-debian
ssh_config:
  user: debian
  identity_file: ~/.ssh/vm_debian
  hosts:
    - hostname: 192.168.122.75
```

```
$ dstack apply -f .dstack/fleet-vm-debian.dstack.yml
```

### Actual behaviour

```
No ssh key specified for host 192.168.122.75
```

### dstack version

03a26e27f09ad74aa18483ba724a138f75d343a5

### Server logs

```shell

```

### Additional information

Introduced in https://github.com/dstackai/dstack/pull/2577

`_remove_fleet_spec_sensitive_info` removes SSH keys from the spec.
