### ISSUE TITLE
[Feature]: GCP Hyperdisk Volumes

### ISSUE THREAD

**Issue by dakota-shop** [dstackai/dstack#2588]
### Problem

Currently, Dstack only supports using `pd-balanced` GCE Disks. For higher performance persistent storage on GCP, we want the ability to specify the underlying disk type (e.g. `hyperdisk-balanced`). 

### Solution

Add the ability to specify the Volume type that the Backend can interpolate into the GCE disk type (instead of hardcoding `pd-balanced`).

### Would you like to help us implement this feature by sending a PR?

Yes

**Comment by dakota-shop** [comment]
## Simple Proposal

- `VolumeConfiguration` gets a new `volume_type` attribute of type `VolumeType`, which is a new `Enum` class containing non-default volume types.  Entries should be prefixed with the backend name (e.g. `gcp_hyperdisk_balanced`) since each volume type will require backend-specific support.
- Example:
```yaml
type: volume
name: myhypervol
backend: gcp
region: us-central1
size: 100GB
volume_type: gcp_hyperdisk_balanced
```
- `volume_type` is optional and defaults to `None`, which means "use the backend's default volume implementation".
- Add validation logic on the Volume that prevents VolumeType entries from being specified on an incompatible backend. There are many possible approaches for this:
	- Validate based on the enum value prefix (or `VolumeType` could be implemented as a richer datatype that refers to the `Backend` Enum)
	- Delegate VolumeType compatibility validation to the `Backend` ABC - the default implementation supports no VolumeTypes besides the backend-specific default (`volume_type = None`).

This is easy to implement, but I wonder whether there is a more robust, generalizable way to specify backend-specific resource options.

## Extensible Proposal

- Create a field containing backend-specific volume options.
- Example:
```yaml
type: volume
name: myhypervol
backend: gcp
region: us-central1
size: 100GB
backend_options:
  gcp:
    volume_type: hyperdisk-balanced
```

- Because options are explicitly backend-specific, it is easy to delegate options validation to the Backend implementation.
- The data type of the proposed `backend_options` field could be `Dict[str, BackendSpecificVolumeOptions]`, where `BackendSpecificVolumeOptions` could either be truly Backend-specific (i.e. `Text` or similar to Dstack Core) or could be implemented naively as `Dict[str, str]`. 
- This approach has the advantage of potentially being reusable for other resource types.

**Comment by r4victor** [comment]
@dakota-shop, thanks for a detailed proposal! We should go with Extensible since we plan to support more backend-specific volume options (e.g. various parameters for AWS EBS volumes), and it would be much better covered by Extensible than Simple.

Some comments on how I'd implement it:
* Rename `backend_options` to `options` to keep it concise. All non-backend-specific parameters are top-level anyway.
* We don't have backend-specific options in other configurations yet, but we do have different backend configs, and that can be taken for reference. Every backend can define `*VolumeOptions` models with `type/volume_type`:
  
  ```yaml
  options:
    type: hyperdisk
    variant: balanced
  ```
  
  These are to be aggregated into `VolumeOptions` union and it will be parsed using `options.type` as discriminator. The dstack core needs to know about backend-specific `*VolumeOptions` models so that the API reference and json schema (configurations autocomplete) automatically document `options` structure.
* `options.type` must be unique, so we can prefix it with backend name `type: gcp_hyperdisk`. But for major clouds, they have different names for their persistence solutions, so we can go without a prefix as well.
* For volumes in particular, we don't need to specify multiple `options.type` for different backends (at least for now) since every configurations specifies one `backend`. But it may be needed in the future or for other configuration types. We can then extend options to list:
  ```yaml
    options:
      - type: hyperdisk
        variant: balanced
      - type: ebs
        variant: io2
  ```
  A backend should have no problem filtering out its options.
* Not sure if it should be `type: hyperdisk` with subtypes like `variant: balanced` or `type: hyperdisk_balanced` but I'm inclined to former since we'll support different types like `persistent_disk`, `hyperdisk`, `filestore`, etc, and I think it would be easier to reason about than having multiple variations of each in `type`.
