### ISSUE TITLE
[Bug]: Instances with `blocks` feature cannot be used for multi-node runs

### ISSUE THREAD

**Issue by un-def** [dstackai/dstack#2650]
### Steps to reproduce

```yaml
# fleet.dstack.yml
type: fleet
name: fleet-cloud-2x
placement: cluster
nodes: 2
blocks: auto
resources:
  cpu: 2..
  gpu: 0
  memory: 1GB..
  disk: 1GB..
```

```yaml
# task.dstack.yml
type: task
name: iperf3
image: debian
nodes: 2
commands:
  - |
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y iperf3
    if [ $DSTACK_NODE_RANK -eq 0 ]; then
      iperf3 -s -1
    else
      sleep 5
      iperf3 -c $DSTACK_MASTER_NODE_IP -t 30
    fi
resources:
  cpu: 1..
  memory: 1GB..
  gpu: 0
  disk: 1GB..
```

1. `dstack apply -f fleet.dstack.yml`
    ```
     FLEET           INSTANCE  BACKEND      RESOURCES                PRICE   STATUS    CREATED
     fleet-cloud-2x  0         vultr (ewr)  cpu=2 mem=2GB disk=65GB  $0.021  0/2 busy  11:55
                     1         vultr (ewr)  cpu=2 mem=2GB disk=65GB  $0.021  0/2 busy  11:55
    ```
2. `dstack apply --reuse -f task.dstack.yml`

### Actual behaviour

```
No matching instance offers available. Possible reasons: https://dstack.ai/docs/guides/troubleshooting/#no-offers
```

### Expected behaviour

```
 #  BACKEND      RESOURCES                INSTANCE TYPE     PRICE
 1  vultr (ewr)  cpu=2 mem=2GB disk=65GB  vc2-2c-2gb (2/2)  $0.021  idle
 2  vultr (ewr)  cpu=2 mem=2GB disk=65GB  vc2-2c-2gb (2/2)  $0.021  idle
```

### dstack version

0.19.9

### Server logs

```shell

```
