### ISSUE TITLE
[Bug]: GPU instances start without traffic and scale down while processing – inconsistent autoscaling behavior

### ISSUE THREAD

**Issue by nowayitsreal** [dstackai/dstack#2656]
### Steps to reproduce

Reproduction Steps

1. Run the server: dstack server --host 0.0.0.0
2. Apply the gateway config.
3. Apply the service config: dstack apply -f dstack.yml
4. Wait without making any requests.
5. GPU machines scale up automatically, first time it is definetely ok, but when it shuts down, after a while i scales up again without traffic.
6. While handling traffic, scale-down still occurs based on delay, causing failures.

### Expected behaviour

Hi team,

I'm setting up a self-hosted dstack server with both the gateway and autoscaling features enabled. While the setup worked as expected on sky.dstack, I'm facing issues on my own machine.

Problem
GPU machines are starting automatically, even when there is no incoming traffic.
This behavior does not match what I experienced on sky.dstack, where everything worked fine with the same service logic.

Autoscaling down happens incorrectly: instances shut down while still handling active requests.(This problems happens on sky.dstack aswell)

What I’ve Tried
I followed the documentation carefully and confirmed that the setup matches the recommended structure.

I had to modify the Docker image slightly on the self-hosted server (e.g., working_dir was not configurable, so I used a custom image on my server).

I monitored network traffic using sudo tcpdump -i any -A -s 0 'tcp port 63631' and verified that no requests were hitting the service, yet the GPU machine still spins up.

Additionally, when scaling down, if new requests arrive or if a job is still running, the instance still shuts down, leading to failures. I had to implement error handling and requeue logic on my side to work around this issue.

Configurations
~/.dstack/server/config.yml:

```
projects:
  - name: project
    backends:
      - type: vastai
        regions: []
        creds:
          type: api_key
          api_key: MY_API_KEY

      - type: runpod
        regions: []
        community_cloud: true
        creds:
          api_key: MY_API_KEY

      - type: cudo
        regions: [no-luster-1, se-smedjebacken-1, gb-london-1, ...]
        project_id: project
        creds:
          type: api_key
          api_key: MY_API_KEY

      - type: aws
        creds:
          type: access_key
          access_key: MY_ACCESS_KEY
          secret_key: MY_SECRET_KEY

default_permissions:
  allow_non_admins_create_projects: true
  allow_non_admins_manage_ssh_fleets: true
```

dstack.yml

```
type: service
port: 63631
image: MYIMAGE

resources:
  gpu: 24GB..48GB
  cpu: 4..
  memory: 8GB..

env:
  MY_ENV_VAR

max_price: 0.50

replicas:
  min: 0
  max: 50

scaling:
  metric: rps
  target: 2
  scale_up_delay: 5
  scale_down_delay: 500
```
gateway.dstack.yml

```
type: gateway
name: project-gateway
domain: gateway.project.me
default: true
backend: aws
region: eu-north-1
```

Reproduction Steps
Run the server: dstack server --host 0.0.0.0

Apply the service config: dstack apply -f dstack.yml

Apply the gateway config.

Wait without making any requests.

GPU machines scale up automatically, without traffic.

While handling traffic, scale-down still occurs based on delay, causing failures.

Notes
The scale-down issue also occurs on sky.dstack.

Changing the scaling.metric to higher values like rps: 10 still causes unnecessary scale-ups.

Would appreciate any guidance or if there's anything I might be missing in the config.

Thanks a lot!

### dstack version

0.19.9
