### ISSUE TITLE
[Bug]: Service shown as `terminated` after scaling to 0 replicas

### ISSUE THREAD

**Issue by jvstme** [dstackai/dstack#2661]
### Steps to reproduce

1. Run the service.
   ```yaml
   type: service
   port: 80
   image: nginx

   replicas: 0..1
   scaling:
     metric: rps
     target: 2
   ```
1. Request it a few times to make it scale up to 1 replica.
1. Wait until it scales down to 0 replicas.
1. Check `dstack ps`.

### Actual behaviour

The run status is shown as `terminated`.
```shell
> dstack ps
 NAME             BACKEND         RESOURCES                        PRICE    STATUS      SUBMITTED   
 afraid-parrot-1  gcp (us-west4)  cpu=2 mem=8GB disk=100GB (spot)  $0.0069  terminated  6 hours ago
```

Although the run is not actually terminated, only the latest replica is.

![Image](https://github.com/user-attachments/assets/77828ba0-fa32-409f-b0eb-4e4d13fff0d9)

### Expected behaviour

The run status is shown as `pending`.

### dstack version

master

### Server logs

```shell

```
