### ISSUE TITLE
Distributed Training Fails on InfiniBand with the default Docker image

### ISSUE THREAD

**Issue by Bihan** [dstackai/dstack#2712]
### How to Reproduce
1. Create Cluster with below config:
```
type: fleet
name: nebuis-fleet
nodes: 2
placement: cluster
resources:
  gpu: 80GB:8
  disk: 500GB
```
2. Run Distributed Training task with below config:

```
type: task
name: trl-train-fsdp-distrib

# Size of the cluster
nodes: 2

python: 3.12
nvcc: true

# Required environment variables
env:
  - HF_TOKEN
  - WANDB_API_KEY
  - HUB_MODEL_ID
  - MODEL_ID=meta-llama/Llama-3.1-8B
  - ACCELERATE_LOG_LEVEL=info
  - NCCL_DEBUG=INFO
# Commands of the task
commands:
  - pip install torch==2.6.0
  - pip install --no-build-isolation flash_attn
  - pip install transformers bitsandbytes peft wandb
  - git clone https://github.com/huggingface/trl
  - cd trl
  - pip install .
  - |
    accelerate launch \
      --config_file=examples/accelerate_configs/fsdp1.yaml \
      --main_process_ip=$DSTACK_MASTER_NODE_IP \
      --main_process_port=8008 \
      --machine_rank=$DSTACK_NODE_RANK \
      --num_processes=$DSTACK_GPUS_NUM \
      --num_machines=$DSTACK_NODES_NUM \
      trl/scripts/sft.py \
      --model_name $MODEL_ID \
      --dataset_name OpenAssistant/oasst_top1_2023-08-25 \
      --dataset_text_field="text" \
      --per_device_train_batch_size 1 \
      --per_device_eval_batch_size 1 \
      --gradient_accumulation_steps 4 \
      --learning_rate 2e-4 \
      --report_to wandb \
      --bf16 \
      --max_seq_length 1024 \
      --attn_implementation flash_attention_2 \
      --logging_steps=10 \
      --output_dir /checkpoints/llama31-ft \
      --hub_model_id $HUB_MODEL_ID \
      --torch_dtype bfloat16

resources:
  gpu: 80GB:8
  disk: 500GB
  shm_size: 128GB

volumes:
  - /checkpoints:/checkpoints
```

### Actual Results
In the current setup using default docker image, NCCL fails to detect and initialize InfiniBand. Instead, it falls back to using TCP/IP sockets. The logs indicate missing network plugins and InfiniBand libraries, as shown below:

```
NCCL INFO NET/Plugin: No plugin found (libnccl-net.so)
NCCL INFO NET/Plugin: Plugin load returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory : when loading libnccl-net.so
NCCL INFO NET/Plugin: Using internal network plugin.
NCCL INFO Comm config Blocking set to 1
NCCL INFO Failed to open libibverbs.so[.1]
NCCL INFO NET/Socket : Using [0]dstack-default-:192.168.0.28<0>
NCCL INFO Using non-device net plugin version 0
NCCL INFO Using network Socket
```

A full log is available in the attached
[actual_output.txt](https://github.com/user-attachments/files/20555052/actual_output.txt)

### Expected Results
NCCL is expected to detect and initialize InfiniBand (IB) interfaces. When properly configured, the logs should include entries like:

`NCCL INFO NET/IB : Using [0]mlx5_0:1/IB/SHARP [1]mlx5_1:1/IB/SHARP [2]mlx5_2:1/IB/SHARP [3]mlx5_3:1/IB/SHARP [4]mlx5_4:1/IB/SHARP [5]mlx5_5:1/IB/SHARP [6]mlx5_6:1/IB/SHARP [7]mlx5_7:1/IB/SHARP`

A full example of expected output is available in the attached

[expected_output.txt](https://github.com/user-attachments/files/20555082/expected_output.txt)

### Description
In a distributed training setup with TRL or Axolotl, the default image fails to initialize NCCL over InfiniBand and instead falls back to TCP/IP sockets. The logs show errors such as No plugin found (`libnccl-net.so`) and Failed to open `libibverbs.so[.1]`, indicating missing NCCL network plugin support and InfiniBand drivers. In contrast, the `dstackai/efa` image initializes NCCL over InfiniBand successfully.

**Comment by r4victor** [comment]
I confirm it's reproduced with a simple pytorch training on nebius 2x H100:80GB:8 cluster:

```yaml
type: task
nodes: 2
env:
  - NCCL_DEBUG=INFO
commands:
  - |
    git clone https://github.com/r4victor/pytorch-distributed-resnet.git
    cd pytorch-distributed-resnet
    mkdir -p data && mkdir -p saved_models && cd data && wget -c --quiet https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz && tar -xvzf cifar-10-python.tar.gz
    cd ..
    pip3 install -r requirements.txt torch
    time torchrun --nproc_per_node=${DSTACK_GPUS_PER_NODE} --node_rank=${DSTACK_NODE_RANK} --nnodes=${DSTACK_NODES_NUM} --master_addr=${DSTACK_MASTER_NODE_IP} --master_port=8008 resnet_ddp.py --num_epochs 20
    echo Done
resources:
  shm_size: 16GB

```
