### ISSUE TITLE
[Docs] Document `utilization_policy` in `Concepts`

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#2719]
Example:

```
# Terminate runs if utilization is below 10% within an hour
utilization_policy:
  min_gpu_utilization: 10
  time_window: 1h
```

Note: if no value within the window is higher than the minimum threshold for all GPUs, consider GPUs underutilized.
