### ISSUE TITLE
[Feature]: Allow to configure backend defaults

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#2721]
### Problem

Project owners often want to pre-configure certain important defaults. This mainly concerns cost-specific policies such as `inacivity_duration` and `utilization_policy`, `max_duration`, etc.

### Solution

Allow users to configure some backend defaults via backend configuration. Example:

```
projects:
  - name: main
    backends:
      - type: aws
        creds:
          type: default

        defaults:
          inactivity_duration: 1h
          utilization_policy:
            min_gpu_utilization: 10
            time_window: 1h
            max_duration: 
              dev-environment: 1h
              task: 3h
              service: 1w
            max_cost: 2
```

Note, default can be overridden at run configuration level. Later, if we want to let project owners to enforce (override) values, we could support that too via `overrides` (in addition to `defaults`).

### Would you like to help us implement this feature by sending a PR?

No
