### ISSUE TITLE
[Bug]: Volume errors not retried

### ISSUE THREAD

**Issue by jvstme** [dstackai/dstack#2804]
### Steps to reproduce

1. Create a single-attach volume (e.g. AWS) named `test`.
2. Apply the configuration and wait until the run starts.
3. Apply the configuration for the second time.

```yaml
type: dev-environment
ide: vscode
retry: true
volumes:
- test:/test
```

### Actual behaviour

The second run fails with `VOLUME_ERROR`.

### Expected behaviour

The second run is retried until the volume is released by the first run.

### dstack version

0.19.13

### Server logs

```shell

```

### Additional information

Some use cases for retrying volume errors:
- Handling temporary backend errors without stopping the run.
- Enqueuing a run until a volume is released by another run.
