### ISSUE TITLE
[Feature]: Detect `shell` automatically based on the entrypoint of the specified image

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#2829]
### Steps to reproduce

1.

```yaml
type: task
name: train

image: huggingface/trl-latest-gpu

env:
  - MODEL=Qwen/Qwen2.5-0.5B
  - DATASET=stanfordnlp/imdb

commands:
  - source activate trl
  - |
    trl sft --model_name_or_path $MODEL \
        --dataset_name $DATASET \
        --output_dir /output \
        --torch_dtype bfloat16 \
        --use_peft true

resources:
  gpu: H100:1
```

### Actual behaviour

1. Fail as `source` doesn't work with `sh`

One has to add:

```yaml
shell: bash
```

### Expected behaviour

1. It would be a lot more convenient if the shell is detected automatically. Of course only in case it's set in the image as the entrypoint.

### dstack version

Any

### Server logs

```shell

```
