### ISSUE TITLE
[Feature] Allow to specify paths to the folders that must be cached (for the current user, repo and workflow)

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#284]

**Comment by Egor-S** [comment]
Workflow schema proposal

```
workflows:
  - name: cache-pip
    provider: code
    setup:
      - pip install torch
    cache:
      - /root/.cache/pip
      - /workflow/checkpoints
```

Limitations

1. dstack is not responsible for lazy execution
2. dstack caches directories, not commands' artifacts

Questions to be addressed

* [x] When to save cache?
* [x] Is cache a subset of artifacts? Are they related at all?
* [x] How to clear cache?
* [x] How to merge image data, repo data, and cache?
