### ISSUE TITLE
[Feature] Support `repos` in run configurations (and make `dstack init` optional)

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#2851]
**1. Introduce the `repos` property (similar to `files`)**  

```yaml
repos:
  - .:/workflow
```

or 

```yaml
repos:
  - .
```

or

```yaml
repos:
  - repo_path:  .
     path: .
     identity_key: ~/.ssh/id_rsa
```

or

```yaml
repos:
  - repo_path:  .
    identity_key: ~/.ssh/id_rsa
```

or

```yaml
repos:
  - repo_path:  .
    token: {env. GH_TOKEN}
```

> Note, if the repo is remote, `dstack` will try to use the default Git credentials (as it does now) using `~/.config/gh/hosts.yml` or `~/.ssh/id_rsa`.

A repo path can be also a GitHub URL (as it's supported now):

```
repos:
  - repo_path:  https://github.com/huggingface/open-r1
```

or 

```
repos:
  - https://github.com/huggingface/open-r1:/workflow
```

**2. Introduce `ssh_config.identity_file`**  
**3. Deprecate `dstack init`**

> [!WARNING]
> For the first version, let's allow up to one repo. Should help limit changes while addressing the main UX issue.
