### ISSUE TITLE
Support multiple simultaneously configured hub projects in the CLI

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#354]
A part of #338

User should be able to run dstack commands against any project they've configured without the need to reconfigure it with `dstack config`.

I suggest we store multiple project configurations in config.yaml. The current format:

```
backend: hub
project: aws1
token: 12345
url: http://127.0.0.1:3000
```

The new format:

```
projects:
  - name: aws1
    token: 12345
    url: http://127.0.0.1:3000
    default: true
  - name: gcp1
    token: 12345
    url: http://127.0.0.1:3000
```

Users may set default project, or specify `--project` for any dstack command.

I also suggest we remove interactive dstack config since Hub projects are easy to configure with one command.

`dstack config hub --url http://127.0.0.1:3000 --project aws1 --token 12345` will add/edit project configuration. There should also be a way to delete project configuration
