### ISSUE TITLE
[Bug]: Tasks with defined ports fail

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#471]
### dstack version

0.10

### Python version

3.10.10

### Host OS

macOS 13.1

### Host Arch

ARM

## Steps to reproduce:

1. Define a task:

```yml
type: task
setup:
  - pip install -r requirements.txt
ports: [ 7860 ]
commands:
  - gradio app.py --reload
```

2. Run it (either locally or in the cloud)

## Actual behaviour:

```bash
...
ERROR Can't establish SSH tunnel with the container
Aborting...
Aborted
```

This happens because CLI cannot connect via SSH within 1 minute (because setup takes longer than a minute and starts the SSH server after setup).
