### ISSUE TITLE
[Feature] Split `setup` into `build` and `init` properties

### ISSUE THREAD

**Issue by Egor-S** [dstackai/dstack#499]
Build commands (ex. prebuid, ex. setup) must not be magically executed before main commands if ~~pre~~build doesn't exist. The user has to explicitly create ~~pre~~build for configuration. 

Commands that must be always run — could be specified as `init`. For tasks, the user could use `commands`

```yaml
type: dev-environment
ide: vscode
ports:
  - 7860
build: # executed only on `dstack build`
  - "pip install -r requirements.txt"
init:
  - echo "Gradio would be available at http://localhost:7860/"
```

```yaml
type: task
ports:
  - 7860
build: # executed only on `dstack build`
  - "pip install -r requirements.txt"
commands:
  - "gradio app.py &"
```

~~Pre~~build invalidation now becomes the user's responsibility. ~~Pre~~build is chosen based on the repo, configuration path, base image digest, and working dir.

Build policies:
* `--use-build` (default) — fail if no build exists
* `--build` — build if not exist or use existing one
* `--force-build` — always build before use
* `--build-only` — internal policy (for build command)
