### ISSUE TITLE
[Bug]:  No instance type matching requirements 

### ISSUE THREAD

**Issue by dhanush-2501** [dstackai/dstack#559]
### dstack version

0.10.4

### Python version

3.10.9

### Host OS

macOS 13.4.1

### Host Arch

ARM

### What happened?

While executing dstack examples locally, `dstack run ` command resulted in `No instance type matching requirements` even without using profiles.

### Relevant log output

```shell
No instance type matching requirements
```

#### steps to reproduce 
- `dstack start`
- `cd dstack-examples`
- `dstack init`
- `dstack run .`
resulted `No instance type matching requirements`
- `dstack run fastapi-app --reload`
resulted `No instance type matching requirements`

**Comment by dhanush-2501** [comment]
Solved by creating a local profile under the root dir (i.e dstack-examples/.dstack/profiles.yml) 
```
profiles:
  - name: local
    project: local
    resources:
      memory: 1GB
    default: true
```
