### ISSUE TITLE
Allow to use interpolation in environment variables

### ISSUE THREAD

**Issue by kengz** [dstackai/dstack#94]
It is common practice to append to PATH like `PATH=/opt/conda/envs/mnist/bin:$PATH`.
However using this in the workflow file `env` seems ~seems to replace PATH literally without variable interpolation for `$PATH`.~ the workflow does not even run - no log is shown and workflow simply fails.
```
  - name: check-conda
    provider: bash
    env:
      - PATH=/opt/conda/envs/mnist:$PATH
    commands:
      - echo 'checking $PATH'
      - echo $PATH
      - echo 'done'
      - conda env list # this results in `conda not found`
```
