### ISSUE TITLE
[Bug]: dstack run does not respect pool-related `profiles.yml` parameters

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#949]
### dstack version

master

### Python version

3.11

### Host OS

macOS 13.4

### Host Arch

ARM

### What happened?

1. Specify any pool-related parameters in `profiles.yml`. For example, `creation_policy: reuse`:

```
profiles:
  - name: default
    default: true
    spot_policy: auto
    creation_policy: reuse
```

2. Run `dstack run`. See that `creation_policy` is not applied.

The reason is that pool-related parameters defined in `profiles.yml` are not passed from the CLI to the server.
