### ISSUE TITLE
Support absolute path for artifacts

### ISSUE THREAD

**Issue by kengz** [dstackai/dstack#98]
Currently the following workflow will result in empty artifacts:

```yaml
  - name: setup-conda
    help: setup Conda env as artifact for reuse by mounting
    provider: bash
    commands:
      - conda env create --file environment.yml
      - conda clean -tiy
      - export PATH=/opt/conda/envs/mnist/bin:$PATH
      - conda list
    artifacts:
      - path: /opt/conda/envs/mnist
```

commands:
```bash
dstack run setup-condo
#wait for completion
dstack artifacts list <run name>
# it is empty, but should not be
```
