### ISSUE TITLE
Runner doesn't sometimes download all artifact files (due to the "too many open files" error)

### ISSUE THREAD

**Issue by kengz** [dstackai/dstack#99]
**Steps to reproduce**

1. Create `environment.yml`

```
name: mnist-env

channels:
  - pytorch
  - conda-forge
dependencies:
  - autopep8=1.4.4
  - pip=22.2
  - python=3.10.4
  - pytorch=1.12.0
  - torchvision=0.13.0
  - pip:
      - dstack==0.0.7
      - hydra-core==1.2.0
      - pytorch-lightning==1.6.5
```

2. Create `.dstack/workflows.yaml`:

```
workflows:
  - name: mnist-env
    help: setup Conda env as artifact for reuse by mounting
    provider: bash
    commands:
      - conda env create --file environment.yml --prefix env
      - conda clean -tiy
      - conda list
    artifacts:
      - path: env
  - name: mnist-env-test
    provider: bash
    deps:
      - tag: mnist-env
    commands:
      - chmod +x /workflow/env/bin/*
      - /workflow/env/bin/python -c 'import torch; print(torch.__version__)'
```

3. Run `mnist-env` and assign the `mnist-env` tag to it.

4. Run `mnist-env-test` workflow

Expected output:
```
1.12.0
```

Actual output:
```
ModuleNotFoundError: No module named 'site'
```
